language: julia

os:
  - linux
  - osx
  - windows
  
julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - julia: nightly
      os: osx
    - julia: nightly
      os: windows

notifications:
    email: false
