language: julia

os:
  - linux
  - osx
  - windows
  
julia:
  - 1.3
  - 1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - julia: nightly
      os: osx
    - julia: nightly
      os: windows
    - julia: 1.3
      os: osx
    - julia: 1.3
      os: windows
 
branches:
  only:
  - master
  - release-*

notifications:
    email: false
